* Data
** Hyperlinks

Cedars-Sinai dataset. See [[http://www.ncbi.nlm.nih.gov/pubmed/26362074][Machine learning approaches to analyze
histological images of tissues from radical prostatectomies]] for more
details about the curation, annotation and so on.

** Description

There are 225 images. They are tiled with a stride of tile length
/ 2. The class is selected from the center pixel (rounded down if
length is even).

AT masks are used. There are 4 pixel-wise classes.

* Model
  
It is a ResNet model with bottleneck blocks. 

There are 4 bottleneck groups, each one hsa 3 bottleneck blocks, each
block has 3 layers --- an expansion layer which does 1x1 convolution
with a filter size of 128, 256, 512, and 1024 for each group, a
bottleneck layer which does 3x3 convolution with the same number of
filters and a 3x3 convolution with the number of filters set to the
input of the bottleneck block so that dimensions match for the
residual connection.

In total there are $4 \times 3 \times 3 = 36$ layers.

* Results
  
See ipython notebooks for more.

* Research and Benchmarks

What is the meaning of a 4 class mask as in the AT Mask? What is the
different between AT masks and the ST GL masks? How does this
correspond to the Cedars-Sinai paper?

Should I use Jaccard index as well even though it seems wrong and
somewhat convoluted?
